=begin
#Web Forms API version 1.1

#The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

OpenAPI spec version: 1.1.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'docusign_webforms/client/api_client'
require 'docusign_webforms/client/api_error'
require 'docusign_webforms/version'
require 'docusign_webforms/configuration'

# Client Files
require 'docusign_webforms/client/auth/oauth'

# Models
require 'docusign_webforms/models/authentication_method'
require 'docusign_webforms/models/create_instance_request_body'
require 'docusign_webforms/models/http_error'
require 'docusign_webforms/models/http_success'
require 'docusign_webforms/models/instance_source'
require 'docusign_webforms/models/instance_status'
require 'docusign_webforms/models/template_properties'
require 'docusign_webforms/models/web_form'
require 'docusign_webforms/models/web_form_component_type'
require 'docusign_webforms/models/web_form_content'
require 'docusign_webforms/models/web_form_instance'
require 'docusign_webforms/models/web_form_instance_envelopes'
require 'docusign_webforms/models/web_form_instance_list'
require 'docusign_webforms/models/web_form_instance_metadata'
require 'docusign_webforms/models/web_form_metadata'
require 'docusign_webforms/models/web_form_properties'
require 'docusign_webforms/models/web_form_source'
require 'docusign_webforms/models/web_form_state'
require 'docusign_webforms/models/web_form_summary'
require 'docusign_webforms/models/web_form_summary_list'
require 'docusign_webforms/models/web_form_type'
require 'docusign_webforms/models/web_form_user_info'
require 'docusign_webforms/models/web_form_values'

# APIs
require 'docusign_webforms/api/form_instance_management_api'
require 'docusign_webforms/api/form_management_api'

module DocuSign_WebForms
  class << self
    # Customize default settings for the SDK using block.
    #   DocuSign_WebForms.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end