=begin
#Web Forms API version 1.1

#The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

OpenAPI spec version: 1.1.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_WebForms
  class AuthenticationMethod
    
    BIOMETRIC = 'Biometric'.freeze
    EMAIL = 'Email'.freeze
    HTTP_BASIC_AUTH = 'HTTPBasicAuth'.freeze
    KERBEROS = 'Kerberos'.freeze
    KNOWLEDGE_BASED_AUTH = 'KnowledgeBasedAuth'.freeze
    NONE = 'None'.freeze
    PAPER_DOCUMENTS = 'PaperDocuments'.freeze
    PASSWORD = 'Password'.freeze
    RSA_SECURE_ID = 'RSASecureID'.freeze
    SINGLE_SIGN_ON_CA_SITEMINDER = 'SingleSignOn_CASiteminder'.freeze
    SINGLE_SIGN_ON_INFO_CARD = 'SingleSignOn_InfoCard'.freeze
    SINGLE_SIGN_ON_MICROSOFT_ACTIVE_DIRECTORY = 'SingleSignOn_MicrosoftActiveDirectory'.freeze
    SINGLE_SIGN_ON_OTHER = 'SingleSignOn_Other'.freeze
    SINGLE_SIGN_ON_PASSPORT = 'SingleSignOn_Passport'.freeze
    SINGLE_SIGN_ON_SAML = 'SingleSignOn_SAML'.freeze
    SMARTCARD = 'Smartcard'.freeze
    SSL_MUTUAL_AUTH = 'SSLMutualAuth'.freeze
    X509_CERTIFICATE = 'X509Certificate'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = AuthenticationMethod.constants.select { |c| AuthenticationMethod::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #AuthenticationMethod" if constantValues.empty?
      value
    end
  end
end
