=begin
#Web Forms API version 1.1

#The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

OpenAPI spec version: 1.1.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_WebForms
  # Request body containing properties that will be used to create instance.
  class CreateInstanceRequestBody
    # Key-value pairs (where key is the component name and value is the form value) used to create a form instance. For key of type TextBox, Email, Date, Select and RadioButtonGroup the value is of string type. For key of type Number, the value is of number type. For key of type of CheckboxGroup, the value is of type array of string.
    attr_accessor :form_values

    attr_accessor :client_user_id

    attr_accessor :authentication_instant

    attr_accessor :authentication_method

    attr_accessor :assertion_id

    attr_accessor :security_domain

    attr_accessor :return_url

    attr_accessor :expiration_offset

    attr_accessor :send_option

    attr_accessor :brand_id

    # The recipients who will receive the form in email
    attr_accessor :recipients

    # List of tags provided by the user with each request. This field is optional.
    attr_accessor :tags

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'form_values' => :'formValues',
        :'client_user_id' => :'clientUserId',
        :'authentication_instant' => :'authenticationInstant',
        :'authentication_method' => :'authenticationMethod',
        :'assertion_id' => :'assertionId',
        :'security_domain' => :'securityDomain',
        :'return_url' => :'returnUrl',
        :'expiration_offset' => :'expirationOffset',
        :'send_option' => :'sendOption',
        :'brand_id' => :'brandId',
        :'recipients' => :'recipients',
        :'tags' => :'tags'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'form_values' => :'Hash<String, Object>',
        :'client_user_id' => :'String',
        :'authentication_instant' => :'DateTime',
        :'authentication_method' => :'AuthenticationMethod',
        :'assertion_id' => :'String',
        :'security_domain' => :'String',
        :'return_url' => :'String',
        :'expiration_offset' => :'Integer',
        :'send_option' => :'SendOption',
        :'brand_id' => :'String',
        :'recipients' => :'Array<CreateInstanceRequestBodyRecipients>',
        :'tags' => :'Array<String>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'formValues')
        if (value = attributes[:'formValues']).is_a?(Hash)
          self.form_values = value
        end
      end

      if attributes.has_key?(:'clientUserId')
        self.client_user_id = attributes[:'clientUserId']
      end

      if attributes.has_key?(:'authenticationInstant')
        self.authentication_instant = attributes[:'authenticationInstant']
      end

      if attributes.has_key?(:'authenticationMethod')
        self.authentication_method = attributes[:'authenticationMethod']
      end

      if attributes.has_key?(:'assertionId')
        self.assertion_id = attributes[:'assertionId']
      end

      if attributes.has_key?(:'securityDomain')
        self.security_domain = attributes[:'securityDomain']
      end

      if attributes.has_key?(:'returnUrl')
        self.return_url = attributes[:'returnUrl']
      end

      if attributes.has_key?(:'expirationOffset')
        self.expiration_offset = attributes[:'expirationOffset']
      end

      if attributes.has_key?(:'sendOption')
        self.send_option = attributes[:'sendOption']
      end

      if attributes.has_key?(:'brandId')
        self.brand_id = attributes[:'brandId']
      end

      if attributes.has_key?(:'recipients')
        if (value = attributes[:'recipients']).is_a?(Array)
          self.recipients = value
        end
      end

      if attributes.has_key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          form_values == o.form_values &&
          client_user_id == o.client_user_id &&
          authentication_instant == o.authentication_instant &&
          authentication_method == o.authentication_method &&
          assertion_id == o.assertion_id &&
          security_domain == o.security_domain &&
          return_url == o.return_url &&
          expiration_offset == o.expiration_offset &&
          send_option == o.send_option &&
          brand_id == o.brand_id &&
          recipients == o.recipients &&
          tags == o.tags
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [form_values, client_user_id, authentication_instant, authentication_method, assertion_id, security_domain, return_url, expiration_offset, send_option, brand_id, recipients, tags].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = DocuSign_WebForms.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
