=begin
#Web Forms API version 1.1

#The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 

OpenAPI spec version: 1.1.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_WebForms
  class WebFormAdmType
    
    STRING = 'String'.freeze
    BOOLEAN = 'Boolean'.freeze
    DOUBLE = 'Double'.freeze
    DATE_TIME = 'DateTime'.freeze
    ARRAY_OF_STRING = 'ArrayOfString'.freeze
    CHECKBOX_GROUP = 'CheckboxGroup'.freeze
    DATE = 'Date'.freeze
    EMAIL = 'Email'.freeze
    NUMBER = 'Number'.freeze
    RADIO_BUTTON_GROUP = 'RadioButtonGroup'.freeze
    SELECT = 'Select'.freeze
    TEXT_BOX = 'TextBox'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = WebFormAdmType.constants.select { |c| WebFormAdmType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #WebFormAdmType" if constantValues.empty?
      value
    end
  end
end
